/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ZPAfxqvT3R7
 */
import {
  PopoverTrigger,
  PopoverContent,
  Popover,
} from "@/components/ui/popover";

export function Badge({ image, alt }: { image: string; alt: string }) {
  return (
    <div
      onClick={(e) => {
        console.log("clicked", e);
        e.stopPropagation();
        e.preventDefault();
      }}
    >
      <Popover>
        <PopoverTrigger asChild>
          <div className="cursor-pointer hover:opacity-7">
            <img src={image} alt={alt} className="h-4" />
          </div>
        </PopoverTrigger>

        <PopoverContent className="w-fit bg-black p-2 text-white">
          <p className="text-sm leading-none">{alt}</p>
        </PopoverContent>
      </Popover>
    </div>
  );
}
