---
json_rpc_url: https://jarrett-devnet-8fa6.devnet.rpcpool.com/283aba57-34a4-4500-ba4d-1832ff9ca64a
websocket_url: ''
keypair_path: /Users/staccoverflow/7i.json
address_labels:
  '11111111111111111111111111111111': System Program
commitment: finalized
