export default () => ({
  supabaseUrl: process.env.SUPABASE_URL,
  supabaseKey: process.env.SUPABASE_KEY,
  solanaRpcUrl: process.env.SOLANA_RPC_URL,
  solanaRpcUrl2: process.env.SOLANA_RPC_URL2,
  solanaRpcUrl3: process.env.SOLANA_RPC_URL3,
  solanaRpcUrl4: process.env.SOLANA_RPC_URL4,
  solanaRpcUrl5: process.env.SOLANA_RPC_URL5,
  solanaRpcUrl6: process.env.SOLANA_RPC_URL6,
  solanaRpcUrl7: process.env.SOLANA_RPC_URL7,
  solanaRpcUrl8: process.env.SOLANA_RPC_URL8,
  heliusRpcUrl: process.env.HELIUS_RPC_URL,
  solanaGeyserWsRpc1: process.env.SOLANA_GEYSER_WS_RPC1,
  solanaGeyserRpc: process.env.SOLANA_GEYSER_RPC,
  pumpProgramId: process.env.PUMP_PROGRAM_ID,
  twitterClientId: process.env.TWITTER_CLIENT_ID,
  twitterClientSecret: process.env.TWITTER_CLIENT_SECRET,
  twitterRedirectUri: process.env.TWITTER_REDIRECT_URI,
  frontendDomain: process.env.FRONTEND_DOMAIN,
  jwtSecret: process.env.JWT_SECRET,
  jwtExpiresIn: process.env.JWT_EXPIRES_IN,
  prod: process.env.PROD,
  openBookProgramId: process.env.OPEN_BOOK_PROGRAM_ID,
  withdrawAuthorityPrivateKey: process.env.WITHDRAW_AUTHORITY_PRIVATE_KEY,
  raydiumLiquidityPoolAmmProgramId:
    process.env.RAYDIUM_LIQUIDITY_POOL_AMM_PROGRAM_ID,
  raydiumFeeDestinationId: process.env.RAYDIUM_FEE_DESTINATION_ID,
  raydiumMigrationSolFee: process.env.RAYDIUM_MIGRATION_SOL_FEE,
  tgBotApiKey: process.env.TG_BOT_API_KEY,
  tgPumpPalBotApiKey: process.env.TG_PUMP_PAL_BOT_API_KEY,
  tcStartDate: process.env.TC_START_DATE,
  tcEndDate: process.env.TC_END_DATE,
  kingOfTheHillMarketCap: process.env.KING_OF_THE_HILL_MARKET_CAP,
  clientApiUrl: process.env.CLIENT_API_URL,
});
